export const APP_MAIN_DB_CONNECTION = 'APP_MAIN_DB_CONNECTION';

export const ENV_NODE_ENV = 'NODE_ENV';
export const ENV_PORT = 'PORT';
export const ENV_MONGODB_MAIN_DATABASE_URI = 'MONGODB_MAIN_DATABASE_URI';
