export const APPLICATION_MAIN_DB_CONNECTION = 'APPLICATION_MAIN_DB_CONNECTION';

export const ENVIRONMENT_NODE_ENV = 'NODE_ENV';
export const ENVIRONMENT_PORT = 'PORT';
export const ENVIRONMENT_MONGODB_MAIN_DATABASE_URI = 'MONGODB_MAIN_DATABASE_URI';
